version: "3"
services:
  automation:
    build: .
    image: python:3.8-alpine
    ports:
      - 5000:5000
    volumes:
      - data:/monstersgame
    deploy:
      restart_policy:
        condition: on-failure
        delay: 300s
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  data: