known_enemies = [
    "AlissonBRA",
    "Lordmam",
    "KitbreaK",
    "alexdelta",
    "Drakodragon",
    "bisket",
    "cadaveria",
    "dark87",
    "Marckinhos",
    "Mona Dark",
    "Illuminus",
    "Lilianne",
    "PedroMMP",
    "Lady Mary",
    "Salazar Slypherin",
    "Linuar",
    "Femme",
    "Hans",
    "Mohr",
    "Reasing",
    "Hauer",
    "lino1542",
    "XxXMaGnAtAxXx",
    "Winterfell",
    "XxMorganaxX",
    "Mrs.StreSsiTu",
    "CrEaToR",
    "Lizza",
    "Deymon",
    "Dehssa",
    "Yuricinho",
    "whitevampir13",
    "The_Paladino",
    "Gladiator28",
    "lord_lmandu",
    "x_bloon",
    "shaga",
    "Arachna",
    "Vinicius",
    "iZ)Luar*",
    "pormenores",
    "ZigFryd"
]
